#!/bin/sh
# Regenerate lib/db/migrations/000_base.sql — what a fresh database is given
# by deploy/deploy.sh instead of replaying every migration. Run after a schema
# change, against a local database that has had push + every migration.
set -eu
DB="${1:-menu4u}"
OUT="$(dirname "$0")/../../lib/db/migrations/000_base.sql"
{
  echo "-- The whole schema of a fully migrated database, for a fresh install."
  echo "-- Generated by scripts/ops/dump-base-schema.sh — do not edit by hand."
  docker exec wam-postgres pg_dump -U wam -d "$DB" --schema-only --no-owner --no-acl --exclude-table=schema_migrations \
    | grep -vE '^(\\restrict|\\unrestrict|SET transaction_timeout)'
} > "$OUT"
echo "wrote $OUT"
